x-base: &base
  build:
    dockerfile: develop.Dockerfile
  entrypoint: echo 'ok!'
  tty: true
  stdin_open: true
  volumes:
    - ./:/app
    - /app/node_modules
  working_dir: /app
  env_file: 
    - /.env
  environment:
    NODE_ENV: development
    CHOKIDAR_USEPOLLING: "1"
    CHOKIDAR_INTERVAL: "300"
    AMQP_URL: amqp://guest:guest@rabbitmq:5672?frameMax=8192
    BASE_URL: http://web:9876
    REDIS_URL: redis://redis:6379
    STORAGE_ENDPOINT: https://af1ce4a18c7a153046fbdc9ce50db632.r2.cloudflarestorage.com/
    GOOGLE_APPLICATION_CREDENTIALS: ${GOOGLE_APPLICATION_CREDENTIALS}

services:
  cloud:
    <<: *base
    restart: on-failure
    entrypoint:
      - sh
      - -lc
      - yarn install --check-files && yarn cloud-dev
    ports:
      - 9876:9876
      - 9229:9229
    env_file: 
    - /.env

  rabbitmq:
    image: rabbitmq:4-management-alpine
    restart: on-failure
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq:/var/lib/rabbitmq

  redis:
    image: redis:7-alpine
    restart: on-failure
    volumes:
      - redis:/data
    command: redis-server --appendonly yes
    ports:
      - 6379:6379

volumes:
  rabbitmq:
  redis:
