export const BAILEYS_AUTH_POLICY = Object.freeze({
  authCacheTtlMs: 5_000,
  authIndexFallbackScanLimit: 2,
  signalPruneDefaultTypes: Object.freeze(['pre-key']),
  signalPruneMaxDelete: 5_000,
  signalPrunePreKeyKeepRecent: 5_000,
  signalPruneScanCount: 1_000,
  signalPruneBootstrapEnabled: false,
  signalPruneDailyEnabled: false,
  signalPruneDailyIntervalMs: 24 * 60 * 60_000,
  signalPruneSessionIntervalMs: 24 * 60 * 60_000,
  signalPruneSessionLimit: 100_000,
  signalPurgeDeviceListEnabled: false,
  signalPurgeSessionEnabled: false,
  signalPurgeSenderKeyEnabled: false,
  jidMapEnrichPerSweep: 20,
  jidMapEnrichAuthEnabled: true,
  jidMapEnrichOnStoreEnabled: false,
  watchdogPurgeScanCount: 20,
  watchdogTaskMinIntervalMs: 30_000,
  jidMapEnrichMinIntervalMs: 30_000,
})
