export const TYPE_MESSAGES_TO_PROCESS_FILE = ['imageMessage', 'videoMessage', 'audioMessage', 'documentMessage', 'stickerMessage', 'ptvMessage']

export const TYPE_MESSAGES_MEDIA = ['image', 'audio', 'document', 'video', 'sticker']

export const MESSAGE_STUB_TYPE_ERRORS = [
  'Message absent from node'.toLowerCase(),
  'Invalid PreKey ID'.toLowerCase(),
  'Key used already or never filled'.toLowerCase(),
  'No SenderKeyRecord found for decryption'.toLowerCase(),
  'No session record'.toLowerCase(),
  'No matching sessions found for message'.toLowerCase(),
]

export const TYPE_MESSAGES_TO_READ = [
  'viewOnceMessage',
  'editedMessage',
  'ephemeralMessage',
  'documentWithCaptionMessage',
  'viewOnceMessageV2',
  'viewOnceMessageV2Extension',
  'lottieStickerMessage',
  'imageMessage',
  'videoMessage',
  'audioMessage',
  'stickerMessage',
  'documentMessage',
  'contactMessage',
  'contactsArrayMessage',
  'extendedTextMessage',
  'reactionMessage',
  'locationMessage',
  'liveLocationMessage',
  'listMessage',
  'buttonsMessage',
  'interactiveMessage',
  'listResponseMessage',
  'buttonsResponseMessage',
  'interactiveResponseMessage',
  'conversation',
  'ptvMessage',
  'templateButtonReplyMessage',
  'templateMessage',
  'groupInviteMessage',
  'orderMessage',
  'pollCreationMessage',
  'pollCreationMessageV2',
  'pollCreationMessageV3',
  'pollCreationMessageV5',
  'pollUpdateMessage',
  'eventMessage',
  'scheduledCallCreationMessage',
  'scheduledCallEditMessage',
  'requestPhoneNumberMessage',
  'newsletterAdminInviteMessage',
  'newsletterFollowerInviteMessageV2',
  'questionMessage',
  'questionResponseMessage',
  'questionReplyMessage',
  'statusQuestionAnswerMessage',
  'callLogMesssage',
  'pollResultSnapshotMessage',
  'pollResultSnapshotMessageV3',
  'statusQuotedMessage',
  'statusAddYours',
  'secretEncryptedMessage',
]

export const OTHER_MESSAGES_TO_PROCESS = [
  'protocolMessage',
  'senderKeyDistributionMessage',
  'messageContextInfo',
  'messageStubType',
]
