import { WA_DEFAULTS, WA_IQ_TYPES, WA_XMLNS, type BinaryNode, type WaClient } from 'zapo-js'
import { assertIqResult, findNodeChild, getNodeTextContent } from 'zapo-js/transport'
import type {
  CatalogOrderItem,
  CatalogOrderResolution,
  CatalogVariant,
} from '../catalog/catalog_types'
import { formatCatalogMoney } from '../catalog/catalog_mapper'

// Generated by zapo-js 1.6.1 for the official BizQueryOrder operation.
// The focused test compares this value with the installed Zapo spec so a
// dependency upgrade cannot silently keep a stale persisted document id.
export const ZAPO_BIZ_QUERY_ORDER_DOCUMENT_ID = '26593811266898374'

const text = (value: unknown) => `${value ?? ''}`.trim()

export const decimalMoneyToAmount1000 = (value: unknown): number | undefined => {
  const raw = text(value)
  if (!/^-?\d+(?:\.\d+)?$/.test(raw)) return undefined
  const [integerPart, decimalPart = ''] = raw.split('.')
  const sign = integerPart.startsWith('-') ? -1 : 1
  const integer = Number(integerPart)
  const fraction = Number(`${decimalPart}000`.slice(0, 3))
  if (!Number.isSafeInteger(integer) || !Number.isSafeInteger(fraction)) return undefined
  return integer * 1000 + sign * fraction
}

const positiveInteger = (value: unknown, fallback = 1) => {
  const parsed = Number.parseInt(text(value), 10)
  return Number.isFinite(parsed) && parsed > 0 ? parsed : fallback
}

const variants = (product: any): CatalogVariant[] => (
  Array.isArray(product?.variant_info?.variant_properties)
    ? product.variant_info.variant_properties
      .map((variant: any) => ({ name: text(variant?.name), value: text(variant?.value) }))
      .filter((variant: CatalogVariant) => variant.name && variant.value)
    : []
)

const productImage = (product: any) => {
  const image = Array.isArray(product?.media?.images) ? product.media.images[0] : undefined
  const url = text(image?.request_image_url)
  return /^https?:\/\//i.test(url) ? { url } : undefined
}

const mapProduct = (product: any, orderCurrency?: string): CatalogOrderItem => {
  const quantity = positiveInteger(product?.quantity)
  const currency = text(product?.currency) || orderCurrency
  const unitPrice = decimalMoneyToAmount1000(product?.price)
  const itemVariants = variants(product)
  return {
    product_id: text(product?.id) || 'unknown',
    title: text(product?.name) || text(product?.id) || 'Produto',
    quantity,
    ...(currency ? { currency } : {}),
    ...(unitPrice !== undefined ? {
      unit_price_amount_1000: unitPrice,
      subtotal_amount_1000: unitPrice * quantity,
      formatted_unit_price: formatCatalogMoney(unitPrice, currency),
      formatted_subtotal: formatCatalogMoney(unitPrice * quantity, currency),
    } : {}),
    ...(productImage(product) ? { image: productImage(product) } : {}),
    ...(itemVariants.length ? { variants: itemVariants } : {}),
  }
}

const parseMexData = (response: BinaryNode) => {
  assertIqResult(response, 'mex/BizQueryOrder')
  const result = findNodeChild(response, 'result')
  if (!result) throw new Error('zapo_order_response_missing_result')
  if (`${result.attrs.format || 'json'}` === 'argo') {
    throw new Error('zapo_order_response_argo_not_supported')
  }
  const body = getNodeTextContent(result)
  if (!body) throw new Error('zapo_order_response_empty')
  const payload = JSON.parse(body)
  if (Array.isArray(payload?.errors) && payload.errors.length) {
    throw new Error(`zapo_order_query_failed: ${text(payload.errors[0]?.message) || 'unknown'}`)
  }
  return payload?.data || null
}

export interface ZapoOrderSnapshot {
  orderId?: string | null
  sellerJid?: string | null
  token?: string | null
}

export class ZapoOrderResolver {
  constructor(private readonly client: Pick<WaClient, 'lowlevel'>) {}

  async resolve(order: ZapoOrderSnapshot): Promise<CatalogOrderResolution> {
    const orderId = text(order.orderId)
    const sellerJid = text(order.sellerJid)
    const token = text(order.token)
    if (!orderId || !sellerJid || !token) {
      return { resolution_status: 'summary', items: [] }
    }

    const variables = {
      request: {
        order: {
          jid: sellerJid,
          id: orderId,
          token: { sensitive_string_value: token },
          image_dimensions: { width: 256, height: 256 },
        },
      },
    }
    const query: BinaryNode = {
      tag: 'iq',
      attrs: {
        to: WA_DEFAULTS.HOST_DOMAIN,
        type: WA_IQ_TYPES.GET,
        xmlns: WA_XMLNS.MEX,
      },
      content: [
        {
          tag: 'query',
          attrs: { query_id: ZAPO_BIZ_QUERY_ORDER_DOCUMENT_ID },
          content: JSON.stringify({
            queryId: ZAPO_BIZ_QUERY_ORDER_DOCUMENT_ID,
            variables,
          }),
        },
      ],
    }
    const data = parseMexData(await this.client.lowlevel.query(query, 32_000))
    const resolved = data?.xwa_checkout_get_order_info?.order
    if (!resolved) return { resolution_status: 'summary', items: [] }

    const currency = text(resolved?.price_details?.currency)
      || text(resolved?.products?.[0]?.currency)
      || undefined
    const items = Array.isArray(resolved.products)
      ? resolved.products.map((product: any) => mapProduct(product, currency))
      : []
    return {
      resolution_status: items.length ? 'resolved' : 'summary',
      items,
      ...(currency ? { currency } : {}),
      ...(decimalMoneyToAmount1000(resolved?.price_details?.subtotal_amount) !== undefined ? {
        subtotal_amount_1000: decimalMoneyToAmount1000(resolved.price_details.subtotal_amount),
      } : {}),
      ...(decimalMoneyToAmount1000(resolved?.price_details?.total_amount) !== undefined ? {
        total_amount_1000: decimalMoneyToAmount1000(resolved.price_details.total_amount),
      } : {}),
    }
  }
}
