name: Sync Docs to Wiki

on:
  push:
    branches: [ main, master ]
    paths:
      - 'docs/**'

jobs:
  sync:
    runs-on: ubuntu-latest
    env:
      WIKI_TOKEN: ${{ secrets.WIKI_TOKEN }}
      REPO: ${{ github.repository }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Skip if no WIKI_TOKEN
        if: env.WIKI_TOKEN == ''
        run: |
          echo "WIKI_TOKEN not set; skipping wiki sync."

      - name: Checkout wiki repo
        if: env.WIKI_TOKEN != ''
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}.wiki
          token: ${{ secrets.WIKI_TOKEN }}
          path: wiki

      - name: Sync docs to wiki
        if: env.WIKI_TOKEN != ''
        run: |
          set -euo pipefail
          git config --global user.email "wiki-bot@users.noreply.github.com"
          git config --global user.name "wiki-bot"
          mkdir -p wiki
          find wiki -mindepth 1 -maxdepth 1 -not -name '.git' -exec rm -rf {} +
          # Copy English and pt-BR docs
          cp -r docs/* wiki/ || true
          # Create Home.md with links
          cat > wiki/Home.md <<'EOF'
          # Unoapi Cloud — Documentação

          ## Inglês
          - [Architecture](ARCHITECTURE.md)
          - [Development](DEVELOPMENT.md)
          - [Environment Variables](ENVIRONMENT.md)
          - [Status/Broadcast](STATUS_BROADCAST.md)
          - OpenAPI (YAML): [openapi.yaml](openapi.yaml)
          - Examples: [.env example](examples/.env.example.en)

          ## Português (Brasil)
          - [Arquitetura](pt-BR/ARQUITETURA.md)
          - [Desenvolvimento](pt-BR/DESENVOLVIMENTO.md)
          - [Ambiente (Variáveis)](pt-BR/AMBIENTE.md)
          - [Status/Broadcast](pt-BR/STATUS_BROADCAST.md)
          - Exemplos: [.env exemplo](pt-BR/exemplos/.env.exemplo)
          EOF
          cd wiki
          git add -A
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "docs: sync to wiki"
            git push origin HEAD
          fi
